### ISSUE TITLE
Improving Hide Call button plugin

### ISSUE THREAD

**Issue by Rairof** [janisslsm/vdplugins#1]
Hide call button plugin hides the call, video buttons from user profiles but doesn't hides them from DM titles which makes this plugin seem inconsistent.
Can you please hide these buttons from DM chat titles as well? It will also help in showing longer names and giving more space for platform indicator plugin to work on the DM title bar.
![IMG_20230916_110328](https://github.com/janisslsm/vdplugins/assets/107706560/d2043888-3594-42c7-9a9c-8ef02c153cd0)
Here is an image of call buttons not being hidden even after the plugin is being turned on.

**Comment by janisslsm** [comment]
It was only meant to hide the call buttons from user profiles as those are the only ones I misclicked. I'll add a option to hide the title ones but can't give any ETA.

**Comment by Rairof** [comment]
> It was only meant to hide the call buttons from user profiles as those are the only ones I misclicked. I'll add a option to hide the title ones but can't give any ETA.

That would be really helpful and thanks for that.
Please take your time as there is no rush for it.

**Comment by Rairof** [comment]
I just thought it would be better to have an option to hide those call buttons overall to never misclick anywhere in discord.

**Comment by janisslsm** [comment]
added with bd6c0e3d3e71f6fdf3867490226d08fc65fb5870
