### ISSUE TITLE
bug(vendetta/plugins/HideCallButtons) hiding add friend button

### ISSUE THREAD

**Issue by Rairof** [janisslsm/vdplugins#2]
It hides friend button as well now on 199.14 beta version I'm using now without the user not being a friend. I am not sure why it's happening but disabling the plugin brings back all buttons including calls and add friend buttons as well. Hope it's a small fix.
![Screenshot_2023-10-08-22-08-30-489_dev beefers vendetta-edit](https://github.com/janisslsm/vdplugins/assets/107706560/67b97d08-8ad0-4fff-ae03-a0f8add6cd46)
![Screenshot_2023-10-08-22-08-38-086_dev beefers vendetta-edit](https://github.com/janisslsm/vdplugins/assets/107706560/626587ba-bc51-4c99-891b-d01fe3d7a3b3)

**Comment by janisslsm** [comment]
I'll take a look soon
